services:
  - type: worker
    name: trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: PAPER
        value: true
      - key: ALLOW_TRADING
        value: true
      - key: MODE
        value: live
      - key: MAX_USD_PER_ORDER
        value: 1000
      - key: MAX_DAILY_LOSS
        value: 500